### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by kmryashasvi** [shagun25/SheHeroes#14]
i will so this for all the maintainers.
you can see a sample below
![image](https://user-images.githubusercontent.com/66861659/110197155-a9319280-7e6f-11eb-8ece-b12b5acacef7.png)

**Comment by kmryashasvi** [comment]
Please add label of crosswoc and difficulty label

**Comment by shreyadubey0902** [comment]
can i also work on this

**Comment by kmryashasvi** [comment]
I think, I can do this on my own

**Comment by kmryashasvi** [comment]
This is not for gssoc, this is for crosswoc

**Comment by shagun25** [comment]
> can i also work on this

Assigned to you.

**Comment by shreyadubey0902** [comment]
> > can i also work on this
> 
> Assigned to you.

Thanku....😀
