### ISSUE TITLE
Google Authentication Through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [shagun25/SheHeroes#16]
Hello, I want to add Google Authentication Through Firebase... I noticed that email and password authentication already added, but not google authentication...I also work on google authentication in one of my projects..... So, I think, I can do it correctly..... If I can forward with that, Please assign me to here...I am also a **_GSSOC'21_** participant......Thanks, @shagun25 ......

**Comment by SamarpanCoder2002** [comment]
> Hello, I want to add Google Authentication Through Firebase... I noticed that email and password authentication already added, but not google authentication...I also work on google authentication in one of my projects..... So, I think, I can do it correctly..... If I can forward with that, Please assign me to here...I am also a **_GSSOC'21_** participant......Thanks, @shagun25 ......

Thanks for assign me here.... I am also a GSSOC'21 participant.... Kindly,  add **_GSSOC'21_** label in that issue please..Thank you

**Comment by SamarpanCoder2002** [comment]
> > Hello, I want to add Google Authentication Through Firebase... I noticed that email and password authentication already added, but not google authentication...I also work on google authentication in one of my projects..... So, I think, I can do it correctly..... If I can forward with that, Please assign me to here...I am also a **_GSSOC'21_** participant......Thanks, @shagun25 ......
> 
> Thanks for assign me here.... I am also a GSSOC'21 participant.... Kindly, add **_GSSOC'21_** label in that issue please..Thank you

And to add this feature, I need to access firebase account realted to that project. If you have already a firebase account, kindly make me collaborator in that(my gmail: samarpanofficial2021@gmail.com)...... If not having a firebase account, Then I can proceed with making a new firebase account...Waiting for your response....Thanks

**Comment by shagun25** [comment]
> > > Hello, I want to add Google Authentication Through Firebase... I noticed that email and password authentication already added, but not google authentication...I also work on google authentication in one of my projects..... So, I think, I can do it correctly..... If I can forward with that, Please assign me to here...I am also a **_GSSOC'21_** participant......Thanks, @shagun25 ......
> > 
> > 
> > Thanks for assign me here.... I am also a GSSOC'21 participant.... Kindly, add **_GSSOC'21_** label in that issue please..Thank you
> 
> And to add this feature(Google Authentication Through Firebase), I need to access firebase account realted to that project. If you have already a firebase account, kindly make me collaborator in that(my gmail: [samarpanofficial2021@gmail.com](mailto:samarpanofficial2021@gmail.com))...... If not having a firebase account, Then I can proceed with making a new firebase account...Waiting for your response....Thanks @shagun25

Done

**Comment by SamarpanCoder2002** [comment]
> > > > Hello, I want to add Google Authentication Through Firebase... I noticed that email and password authentication already added, but not google authentication...I also work on google authentication in one of my projects..... So, I think, I can do it correctly..... If I can forward with that, Please assign me to here...I am also a **_GSSOC'21_** participant......Thanks, @shagun25 ......
> > > 
> > > 
> > > Thanks for assign me here.... I am also a GSSOC'21 participant... Kindly, add **_GSSOC'21_** label in that issue, please..Thank you
> > 
> > 
> > And to add this feature(Google Authentication Through Firebase), I need to access firebase account realted to that project. If you have already a firebase account, kindly make me collaborator in that(my gmail: [samarpanofficial2021@gmail.com](mailto:samarpanofficial2021@gmail.com))...... If not having a firebase account, Then I can proceed with making a new firebase account...Waiting for your response....Thanks, @shagun25
> 
> Done

Thanks for adding that...... 
1. Can I store user data via google auth in cloud firestore or not......If you give me that permission to store data..... Please give me access of cloud firestore(Without that I can authenticate with google but not store user data in firestore)....
2. I am also a GSSOC'21 participant.... This project under GSSOC.... Please add **_GSSOC'21_** label and level like **_level 1_** ,**_level 2_** or **_level3_** related to that in that issue...
3. Thanks a lot @shagun25

**Comment by SamarpanCoder2002** [comment]
Please let me know about that @shagun25

**Comment by SamarpanCoder2002** [comment]
> Please let me know about that @shagun25

Thanks for assign labels...I will make pull request soon...Thank u @shagun25

**Comment by SamarpanCoder2002** [comment]
Hello mam @shagun25 , I already added a pull request(#57) related to that..... please review it and if ok, then merge it... Thanks @shagun25
