### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [shagun25/SheHeroes#2]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
@shagun25 Please assign it to me as a part of Cross Woc.

**Comment by muthuannamalai12** [comment]
@shagun25 Please assign it to me as a part of Cross Woc.

**Comment by muthuannamalai12** [comment]
@shagun25 Please assign it to me as a part of Cross Woc.

**Comment by Vrushti24** [comment]
hey can i work on this @shagun25 under gssoc?

**Comment by muthuannamalai12** [comment]
@Shagun Can I work on it as a part of GSSOC
