### ISSUE TITLE
Facebook Authentication Through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [shagun25/SheHeroes#20]
**Describe the feature you'd like to add**
I would like to add Facebook Authentication Through Firebase...... 

**Describe how you will do it**
I will use firebase to authenticate with Facebook... I already worked on that in other projects..... So, I think I can do it

**Additional context**
If I can forward With that, 
1. Please assign me to here
2. Please add the labels like **_gssoc'21_** label and other label of levels like **_level 1_** or **_level 2_** or **_level 3_**(Related to the issue) to here..... I am gssoc'21 participant...... 

Waiting for your response..... Thank you @shagun25

**Comment by shagun25** [comment]
> **Describe the feature you'd like to add**
> I would like to add Facebook Authentication Through Firebase......
> 
> **Describe how you will do it**
> I will use firebase to authenticate with Facebook... I already worked on that in other projects..... So, I think I can do it
> 
> **Additional context**
> If I can forward With that,
> 
> 1. Please assign me to here
> 2. Please add the labels like **_gssoc'21_** label and other label of levels like **_level 1_** or **_level 2_** or **_level 3_**(Related to the issue) to here..... I am gssoc'21 participant......
> 
> Waiting for your response..... Thank you @shagun25

Not required as far now.
