### ISSUE TITLE
Add   default contacts for sending message and call

### ISSUE THREAD

**Issue by shagun25** [shagun25/SheHeroes#28]

**Comment by keshavgbpecdelhi** [comment]
Hi, What exactly we have to do in this. And if possible assign it to me, i will try to work on that;

**Comment by hiashutoshsingh** [comment]
Dumhttps://github.com/shagun25/SheHeroes/issues/35

**Comment by hiashutoshsingh** [comment]
Duplicate issue  - https://github.com/shagun25/SheHeroes/issues/35

**Comment by keshavgbpecdelhi** [comment]
What just happened
