### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [shagun25/SheHeroes#3]
I would like to add code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross-woc. Kindly assign it to me.

**Comment by muthuannamalai12** [comment]
@shagun25 Please assign it to me as a part of Cross Woc.

**Comment by muthuannamalai12** [comment]
@shagun25 Please assign it to me as a part of Cross Woc.

**Comment by soukarsha122** [comment]
I would like to work on this issue as a part of GSSOC'21

**Comment by srimontidutta** [comment]
Can I please contribute to this issue? (GSSoC)

**Comment by shagun25** [comment]
@chinmoy12c you first need to ask for an issue ....you can not directly make a PR.

**Comment by chinmoy12c** [comment]
> @chinmoy12c you first need to ask for an issue to assign ....you can not directly make a PR.

Oh, sorry for that  😅 😅

**Comment by chinmoy12c** [comment]
Thanks for assigning @shagun25 :) , could you also please add the ```gssoc21``` label 😄
