### ISSUE TITLE
Record video in foreground

### ISSUE THREAD

**Issue by shagun25** [shagun25/SheHeroes#33]
**Feature:**  - Record video in foreground

**Expected Behaviour:**  - Record video when the user clicks the in a foreground state, then save it to the local store in the app.

**Comment by nathsagar24** [comment]
I would like to work on this issue. Can you please assign it to me? I am a participant of Gssoc and CrossWoc.

**Comment by hiashutoshsingh** [comment]
@nathsagar24 How you will be implementing this? Let's discuss your approach.
