### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [shagun25/SheHeroes#39]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by shagun25** [comment]
> Hi ! I would like to create a file named contributing.md which will
> Add the following -
> 
> 1.Difference between GIT and GITHUB
> 2.How to clone,fork repository
> 3.How to create a branch and then use git push to push to repo
> 4.Create a PR
> 5.Squash commits in a single issue into one
> 6, Updating the forked and local repo as the updations are made in the upstream
> I would like to work on this as a part of GSSOC'21

Already there.
