### ISSUE TITLE
Add Issue And PR Tempaltes

### ISSUE THREAD

**Issue by muthuannamalai12** [shagun25/SheHeroes#4]
Would like to add issue and pr templates to these project that will basically explain the type of issue and its description and also the type of pr the set of checklist that it obeys and its description

Kindly assign this to me as a part of Cross-Woc. I would love to do it

**Comment by shagun25** [comment]
okay . Go for it.

**Comment by kanak22** [comment]
Can I work on this? I would like to contribute to this. If it's open kindly assign it to me
