### ISSUE TITLE
Create a web template for Sheroes App.

### ISSUE THREAD

**Issue by shagun25** [shagun25/SheHeroes#45]
**Feature:** - Web template 
**Expected Behaviour:**  - A web template for the SheHeroes project. This would contain pages including its feature, necessary links, about the project, contact person.

**Ref:**
https://in.pinterest.com/pin/446067538069613843/ - UI should be shown like this.
https://www.duit.io/ - content should be managed like this

POINTS-25

**Comment by Ayushisood** [comment]
Hii @shagun25 , I would like to work on it as a gssoc'21 participant.
Kindly assign this task to me.
I am good in frontend.
Looking forward to positive response.

**Comment by shagun25** [comment]
> Hii @shagun25 , I would like to work on it as a gssoc'21 participant.
> Kindly assign this task to me.
> I am good in frontend.
> Looking forward for positive response.

Hey assigned to you. Kindly share your template before starting or having doubts discuss in discord group.

**Comment by Ayushisood** [comment]
> > Hii @shagun25 , I would like to work on it as a gssoc'21 participant.
> > Kindly assign this task to me.
> > I am good in frontend.
> > Looking forward for positive response.
> 
> Hey assigned to you. Kindly share your template before starting or having doubts discuss in discord group.

Okay thanks! will get back to you with the template soon.

**Comment by Ayushisood** [comment]
Hey @shagun25  Here is the template , I would like to work with...
Please check , Can i go ahead with this?
![2021-03-17 (1)](https://user-images.githubusercontent.com/63868702/111478731-58b31280-8756-11eb-9e89-f24b34f6bce8.png)

**Comment by Ayushisood** [comment]
Hey @shagun25 I have checked the description but when i clicked the template it is showing the page not found!!
Any suggestions what can be done.

**Comment by shagun25** [comment]
> Hey @shagun25 I have checked the description but when i clicked the template it is showing the page not found!!
> Any suggestions what can be done.

Connect with me on discord.

**Comment by Ayushisood** [comment]
@shagun25  Can I start working on any template ??

**Comment by shagun25** [comment]
> @shagun25 Can I start working on any template ??

Already provided you Downloads of Ui .Have you check those...Only work after checking it.

**Comment by Ayushisood** [comment]
> **Feature:** - Web template
> **Expected Behaviour:** - A web template for the SheHeroes project. This would contain pages including its feature, necessary links, about the project, contact person.
> 
> **Ref:**
> https://in.pinterest.com/pin/446067538069613843/ - UI should be shown like this.
> https://www.duit.io/ - content should be managed like this
> 
> POINTS-25

@shagun25  You meant by these references??
I have checked these ref

**Comment by Ayushisood** [comment]
![2021-03-21 (2)](https://user-images.githubusercontent.com/63868702/111903135-bef5a900-8a66-11eb-81fb-5df249ac99d9.png)
 when i clicked on the image its showing   -----
![2021-03-21 (3)](https://user-images.githubusercontent.com/63868702/111903157-d6349680-8a66-11eb-8bd4-8accdc906d57.png)

**Comment by Ayushisood** [comment]
[check](file:///C:/Users/sooda/Downloads/Template-SheHeroes/template-sheHeroes/index.html)

**Comment by Ayushisood** [comment]
@shagun25

[template-sheHeroes.zip](https://github.com/shagun25/SheHeroes/files/6182805/template-sheHeroes.zip)

Please check the index.html file once and let me know what changes are required according to you!

**Comment by shagun25** [comment]
> > **Feature:** - Web template
> > **Expected Behaviour:** - A web template for the SheHeroes project. This would contain pages including its feature, necessary links, about the project, contact person.
> > **Ref:**
> > https://in.pinterest.com/pin/446067538069613843/ - UI should be shown like this.
> > https://www.duit.io/ - content should be managed like this
> > POINTS-25
> 
> @shagun25 You meant by these references??
> I have checked these ref

Provided on discord channel

**Comment by shagun25** [comment]
> @shagun25
> 
> [template-sheHeroes.zip](https://github.com/shagun25/SheHeroes/files/6182805/template-sheHeroes.zip)
> 
> Please check the index.html file once and let me know what changes are required according to you!

I already told you to refer the links first And then implement. Please gave a look of main page i provided you.

**Comment by Ayushisood** [comment]
@shagun25  Please check it again as i have made all the suggested changes.

[SheHeroes-template.zip](https://github.com/shagun25/SheHeroes/files/6209955/SheHeroes-template.zip)
Made changes according to this design
![WhatsApp Image 2021-03-14 at 01 16 28 (1)](https://user-images.githubusercontent.com/63868702/112595646-b5868b00-8e30-11eb-9cb7-416fe17b0475.jpeg)

**Comment by Ayushisood** [comment]
Made changes according to this design

![2021-03-26](https://user-images.githubusercontent.com/63868702/112596937-7f4a0b00-8e32-11eb-9278-1c6300cc8570.png)

**Comment by Ayushisood** [comment]
@shagun25 Kindly review the changes and do let me know , if other changes are required

**Comment by shagun25** [comment]
> @shagun25 Kindly review the changes and do let me know , if other changes are required

I have reviewed template is looking good .

**Comment by Ayushisood** [comment]
@shagun25 , Done the correction 
Kindly tell me, what data do i need to fill out in the template??

**Comment by shagun25** [comment]
> @shagun25 , Done the correction
> Kindly tell me, what data do i need to fill out in the template??

original screenshots.
real about sections.
feature section explaining the contents in app with brief detailation.
contacts to be added.

**Comment by Ayushisood** [comment]
> > @shagun25 , Done the correction
> > Kindly tell me, what data do i need to fill out in the template??
> 
> original screenshots.
> real about sections.
> feature section explaining the contents in app with brief detailation.
> contacts to be added.
> once done kindly review the work.

@shagun25 Made all the changes, since i do not have the direct link of the app, so did not provide the link for download the app section..
Kindly check the modified html file and do tell me what furthur changes are required.
[SheHeroes-template (2).zip](https://github.com/shagun25/SheHeroes/files/6250351/SheHeroes-template.2.zip)

**Comment by Ayushisood** [comment]
@shagun25 , Kindly review the changes

**Comment by shagun25** [comment]
> @shagun25 , Kindly review the changes

Is get in touch and subscribe connected with backend?

**Comment by shagun25** [comment]
> > @shagun25 , Kindly review the changes
> 
> Is get in touch and subscribe connected with backend?

you have done great job very clean ui.

**Comment by Ayushisood** [comment]
> > > @shagun25 , Kindly review the changes
> > 
> > 
> > Is get in touch and subscribe connected with backend?
> 
> you have done great job very clean ui.

@shagun25  Thank you :)
Should I make a PR now, and also tell me how to connect subscribe with backend(any link or any folder in the codebase for backend)??

**Comment by Ayushisood** [comment]
> > > > @shagun25 , Kindly review the changes
> > > 
> > > 
> > > Is get in touch and subscribe connected with backend?
> > 
> > 
> > you have done great job very clean ui.
> 
> @shagun25 Thank you :)
> Should I make a PR now, and also tell me how to connect subscribe with backend(any link or any folder in the codebase for backend)??

@shagun25 Should I make PR??

**Comment by shagun25** [comment]
> > > > @shagun25 , Kindly review the changes
> > > 
> > > 
> > > Is get in touch and subscribe connected with backend?
> > 
> > 
> > you have done great job very clean ui.
> 
> @shagun25 Thank you :)
> Should I make a PR now, and also tell me how to connect subscribe with backend(any link or any folder in the codebase for backend)??

You can use firebase for ease of access.
