### ISSUE TITLE
Fake Call

### ISSUE THREAD

**Issue by shagun25** [shagun25/SheHeroes#49]
Call yourself using a fake name to get out of unpleasant situations .
Inside this :
1. Enter a fake name
2. Timer
You Can take help from UI provided

<h2 align="center" id="ScreenShots"></h2>

|||
|---|---|
|<h3 align="center">Fake Call</h3><img width="1440" alt="Screen Shot 2020-11-21 at 10 00 32 PM" src="https://user-images.githubusercontent.com/63994999/111460200-b2f5a880-8741-11eb-980d-0c50a6ae3780.jpeg">|<h3 align="center">Timer</h3><img width="1440" alt="Screen Shot 2020-11-21 at 10 00 20 PM" src="https://user-images.githubusercontent.com/63994999/111460086-8e99cc00-8741-11eb-8da5-ecc4a184e7a5.jpeg">|
POINTS-25

**Comment by D-Ajay-Kumar** [comment]
Do we just have to create a screen which looks like a person is calling? If that's the case then I can try my hand at this.

**Comment by shagun25** [comment]
> Do we just have to create a screen which looks like a person is calling? If that's the case then I can try my hand at this.

Yes we need to show a Fake screen which seems like actual call is there and should use the phone ringtone we set for original calls.

**Comment by SamarpanCoder2002** [comment]
> > Do we just have to create a screen which looks like a person is calling? If that's the case then I can try my hand at this.
> 
> Yes we need to show a Fake screen which seems like actual call is there and should use the phone ringtone we set for original calls.

Can I forward With that? Please assign me to here @shagun25

**Comment by hiashutoshsingh** [comment]
> Do we just have to create a screen which looks like a person is calling? If that's the case then I can try my hand at this.

would you like to take this up @D-Ajay-Kumar , otherwise we have this assign to @SamarpanCoder2002

**Comment by D-Ajay-Kumar** [comment]
Sure please go ahead with @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
Thanks for assign me @hiashutoshsingh

**Comment by SamarpanCoder2002** [comment]
@shagun25 @hiashutoshsingh .... Fake call functionality successfully added...please review and merge it...Thank u

**Comment by SamarpanCoder2002** [comment]
> @shagun25 @hiashutoshsingh .... Fake call functionality successfully added...please review and merge it...Thank u

Hello @shagun25 @hiashutoshsingh .... I make changes according to you...please review it and merge it..Thank u @hiashutoshsingh

**Comment by SamarpanCoder2002** [comment]
@hiashutoshsingh  @shagun25 UI Modified in pull request.... please check it, review it and merge it(#69 )
