### ISSUE TITLE
Record video in background

### ISSUE THREAD

**Issue by hiashutoshsingh** [shagun25/SheHeroes#54]
Feature: - Record video in background

Expected Behaviour: - Record video when the user clicks any button in the background, then save it to the local store in the app.
POINTS-25

**Comment by SamarpanCoder2002** [comment]
> Feature: - Record video in background
> 
> Expected Behaviour: - Record video when the user clicks any button in the background, then save it to the local store in the app.

I am a gssoc'21 participant....If I can proceed with that, please assign me @hiashutoshsingh @shagun25

**Comment by SamarpanCoder2002** [comment]
> > Feature: - Record video in background
> > Expected Behaviour: - Record video when the user clicks any button in the background, then save it to the local store in the app.
> 
> I am a gssoc'21 participant....If I can proceed with that, please assign me @hiashutoshsingh @shagun25

Thanks for assign me...I will make a pull request soon

**Comment by SamarpanCoder2002** [comment]
Hello @hiashutoshsingh @shagun25 ...I already made a pull request...please check it
