### ISSUE TITLE
Capture image in background

### ISSUE THREAD

**Issue by hiashutoshsingh** [shagun25/SheHeroes#56]
Feature: Capture image in the background

Expected Behaviour: In case of emergency capture image in the background and save it in the local storage of the app.
POINTS-25

**Comment by SamarpanCoder2002** [comment]
> Feature: Capture image in the background
> 
> Expected Behaviour: In case of emergency capture image in the background and save it in the local storage of the app.

@hiashutoshsingh Can I proceed With that issue??? I am also a gssoc'21 participant....please assign it to me

**Comment by shagun25** [comment]
> > Feature: Capture image in the background
> > Expected Behaviour: In case of emergency capture image in the background and save it in the local storage of the app.
> 
> @hiashutoshsingh @shagun25 Can I proceed With that issue??? I am also a gssoc'21 participant....please assign it to me

Assigned to you.

**Comment by SamarpanCoder2002** [comment]
@shagun25 @hiashutoshsingh ... I already added pull request regarding to that issue....Please check it out ( #73 )

**Comment by SamarpanCoder2002** [comment]
@shagun25 @hiashutoshsingh Conflicts resolved in pull request #73 ... please take a look
