### ISSUE TITLE
modify gitignore file as per flutter project

### ISSUE THREAD

**Issue by hiashutoshsingh** [shagun25/SheHeroes#58]
**Feature:** Modify gitignore file

**Expected Behaviour:** Add necessary files and folder in gitignore file for a flutter project. There are many things which are missed out in the current one.

**Ref:** https://github.com/flutter/flutter/blob/master/.gitignore

POINTS-15

**Comment by hridhi** [comment]
Hey, can you elaborate ?

**Comment by hridhi** [comment]
Hey, I am interested to take up this issue

**Comment by shagun25** [comment]
> Hey, I am interested to take up this issue , I am one of the GSSoC participant as well

Assigned.
