### ISSUE TITLE
Emergency Hooter

### ISSUE THREAD

**Issue by shagun25** [shagun25/SheHeroes#60]
Get attention in case of emergency situations. Press the activate button to Start the emergency hooter(sound) and flashlight.

**Comment by SamarpanCoder2002** [comment]
> Get attention in case of emergency situations. Press the activate button to Start the emergency hooter and flashlight.

Can I work on that ??? @shagun25 @hiashutoshsingh .... I am also a gssoc'21 participant..... Please assign me to HERE

**Comment by pawan2806** [comment]
Can I work on this under Gssco21? @shagun25 @hiashutoshsingh

**Comment by SamarpanCoder2002** [comment]
Thanks for assign @shagun25 .... I am also a GSSOC'21 particiapant...please raise the required label of this program(like `GSSOC'21` and `label`) ..Thank u @shagun25 @hiashutoshsingh

**Comment by SamarpanCoder2002** [comment]
Hello @shagun25 @hiashutoshsingh .... Is Emergency Hooter means `Emergency Siren` from mobile or `Emergency Call` to someone...Here I little confused..pls help me to know it

**Comment by hiashutoshsingh** [comment]
> Hello @shagun25 @hiashutoshsingh .... Is Emergency Hooter means `Emergency Siren` from mobile or `Emergency Call` to someone...Here I little confused..pls help me to know it

@shagun25 Please elaborate to @SamarpanCoder2002 what's the actual use case here is.
Thanks

**Comment by shagun25** [comment]
> > Hello @shagun25 @hiashutoshsingh .... Is Emergency Hooter means `Emergency Siren` from mobile or `Emergency Call` to someone...Here I little confused..pls help me to know it
> 
> @shagun25 Please elaborate to @SamarpanCoder2002 what's the actual use case here is.
> Thanks

updated issue now .Please check!

**Comment by SamarpanCoder2002** [comment]
> > > Hello @shagun25 @hiashutoshsingh .... Is Emergency Hooter means `Emergency Siren` from mobile or `Emergency Call` to someone...Here I little confused..pls help me to know it
> > 
> > 
> > @shagun25 Please elaborate to @SamarpanCoder2002 what's the actual use case here is.
> > Thanks
> 
> updated issue now .Please check!

Ok got it

**Comment by SamarpanCoder2002** [comment]
@shagun25 @hiashutoshsingh Pul request Added...Please review and merged it

**Comment by SamarpanCoder2002** [comment]
> @shagun25 @hiashutoshsingh Pull request Added (#85 ) ...Please review and merged it...Thanks

Hello @hiashutoshsingh @shagun25.... Why not you raise the labels required for GSSOC21 and level3 related to that issue......??? It's compulsory for that program... Please raise the corresponding labels related to that issue
