### ISSUE TITLE
Add github action to auto label issues 

### ISSUE THREAD

**Issue by muthuannamalai12** [shagun25/SheHeroes#66]
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. Kindly assign me this issue as a part of Girl Script Summer of Code.

**Comment by ankit-kmar** [comment]
Hey, I want to work on this under gssoc21

**Comment by ankit-kmar** [comment]
Is your feature request related to a problem? Please describe.
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

Describe the solution you'd like
A script in .github folder to automate the process.


Please assign me this issue with a GSSOC tag and a level tag.

**Comment by hiashutoshsingh** [comment]
Thanks for the issue, but there is no need for now.
