### ISSUE TITLE
add pendantic file

### ISSUE THREAD

**Issue by hiashutoshsingh** [shagun25/SheHeroes#67]
**Feature:** To pass the project through static analysis 

**Expected Behaviour:** On running **dart analyze** it should give warnings or errors after pedantic integration is done

**Ref:** https://pub.dev/packages/pedantic#stricter-than-effective-dart

**Comment by hiashutoshsingh** [comment]
Also, please resolve all the issues after integrating this in project.

**Comment by Samdid** [comment]
@hiashutoshsingh  I would like to work on this issue, I am a GSSoC21' participant
