### ISSUE TITLE
Sign up screen is overflowing 

### ISSUE THREAD

**Issue by Samdid** [shagun25/SheHeroes#68]
**Describe the bug**
Sign up screen is overflowing.

**Expected behavior**
Sign up screen should not be overflowed

**Screenshots**
![Screenshot_1616784312](https://user-images.githubusercontent.com/70087884/112715991-c35c0f00-8f09-11eb-8850-dd246c150c03.png)

**Additional context**
None

**Comment by Samdid** [comment]
@shagun25  @hiashutoshsingh  Can I fix this? It is looking very bad every time we restarting the app.

**Comment by hiashutoshsingh** [comment]
@Samdid are you having the latest pull of project? I guess this has been fixed a few days back.
