### ISSUE TITLE
I want to add no.of pr's, stars, issues and other in the readme file.

### ISSUE THREAD

**Issue by srisatya1197** [shagun25/SheHeroes#87]
I want to add no.of pr's, stars, issues and other in the readme file.
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115119301-4cc0a780-9fc5-11eb-86fa-30c372f73d98.png)

**Comment by hiashutoshsingh** [comment]
@shagun25 do you want to take this up?

**Comment by srisatya1197** [comment]
@hiashutoshsingh Sir I didn't understand. I opened this issue.

**Comment by srisatya1197** [comment]
@hiashutoshsingh Should I start working on this?

**Comment by shagun25** [comment]
> @shagun25 do you want to take this up?

yeah we can take this. @srisatya go ahead

**Comment by shagun25** [comment]
please add this section at top of readme.

**Comment by srisatya1197** [comment]
@shagun25 How do I do that after merging I really don't know. Should I create another pr?

**Comment by hiashutoshsingh** [comment]
> @shagun25 How do I do that after merging I really don't know. Should I create another pr?

Yes please, create another merge request.

**Comment by srisatya1197** [comment]
@hiashutoshsingh Sorry I didn't understand.

**Comment by hiashutoshsingh** [comment]
> @hiashutoshsingh Sorry I didn't understand.

The new changes you wanted to do raise another PR for that @srisatya1197

**Comment by srisatya1197** [comment]
Ok

**Comment by srisatya1197** [comment]
@hiashutoshsingh @shagun25 you haven't deleted the pr #90 please do it .

**Comment by hiashutoshsingh** [comment]
> @hiashutoshsingh @shagun25 you haven't deleted the pr #90 please do it .

Thanks for reminding.
